---
- name: CONFIGURE IPv6 ADDRESSING
  hosts: CSR1kv
  gather_facts: false
  connection: local

  tasks:
   - name: SET IPv6 ADDRESS 
     ios_config:
       parents: "interface Loopback33"
       lines:
         - description IPv6 ADDRESS - Item 6
         - ipv6 address 3001:ABCD:ABCD:1::1/128
         - ipv6 address fe80::1 link-local

   - name: SHOW IPv6 INTERFACE BRIEF 
     ios_command:
       commands:
         - show ipv6 interface brief
     register: output

   - name: SAVE OUTPUT ./configuraciones/
     copy: 
       content: "{{ output.stdout[0] }}"
       dest: "configuraciones/IPv6_output_{{ inventory_hostname }}.txt"
